"""Initial schema with all models

Revision ID: 564aa650e093
Revises: 
Create Date: 2025-11-15 23:54:18.131750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564aa650e093'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dancers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blaze', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dancers_blaze'), 'dancers', ['blaze'], unique=False)
    op.create_index(op.f('ix_dancers_email'), 'dancers', ['email'], unique=True)
    op.create_index(op.f('ix_dancers_id'), 'dancers', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='tournamentstatus'), nullable=False),
    sa.Column('phase', sa.Enum('REGISTRATION', 'PRESELECTION', 'POOLS', 'FINALS', 'COMPLETED', name='tournamentphase'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'MC', 'JUDGE', name='userrole'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_duo', sa.Boolean(), nullable=False),
    sa.Column('groups_ideal', sa.Integer(), nullable=False),
    sa.Column('performers_ideal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_tournament_id'), 'categories', ['tournament_id'], unique=False)
    op.create_table('performers',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('dancer_id', sa.Uuid(), nullable=False),
    sa.Column('duo_partner_id', sa.Uuid(), nullable=True),
    sa.Column('preselection_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pool_wins', sa.Integer(), nullable=False),
    sa.Column('pool_draws', sa.Integer(), nullable=False),
    sa.Column('pool_losses', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duo_partner_id'], ['performers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dancer_id', 'tournament_id', name='uq_dancer_tournament')
    )
    op.create_index(op.f('ix_performers_category_id'), 'performers', ['category_id'], unique=False)
    op.create_index(op.f('ix_performers_dancer_id'), 'performers', ['dancer_id'], unique=False)
    op.create_index(op.f('ix_performers_id'), 'performers', ['id'], unique=False)
    op.create_index(op.f('ix_performers_tournament_id'), 'performers', ['tournament_id'], unique=False)
    op.create_table('battles',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('PRESELECTION', 'POOLS', 'TIEBREAK', 'FINALS', name='battlephase'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='battlestatus'), nullable=False),
    sa.Column('outcome_type', sa.Enum('SCORED', 'WIN_DRAW_LOSS', 'TIEBREAK', 'WIN_LOSS', name='battleoutcometype'), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['performers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_category_id'), 'battles', ['category_id'], unique=False)
    op.create_index(op.f('ix_battles_id'), 'battles', ['id'], unique=False)
    op.create_index(op.f('ix_battles_phase'), 'battles', ['phase'], unique=False)
    op.create_index(op.f('ix_battles_status'), 'battles', ['status'], unique=False)
    op.create_table('pools',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['performers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_category_id'), 'pools', ['category_id'], unique=False)
    op.create_index(op.f('ix_pools_id'), 'pools', ['id'], unique=False)
    op.create_table('battle_performers',
    sa.Column('battle_id', sa.Uuid(), nullable=False),
    sa.Column('performer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('battle_id', 'performer_id')
    )
    op.create_table('pool_performers',
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('performer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'performer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pool_performers')
    op.drop_table('battle_performers')
    op.drop_index(op.f('ix_pools_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_category_id'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_battles_status'), table_name='battles')
    op.drop_index(op.f('ix_battles_phase'), table_name='battles')
    op.drop_index(op.f('ix_battles_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_category_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_performers_tournament_id'), table_name='performers')
    op.drop_index(op.f('ix_performers_id'), table_name='performers')
    op.drop_index(op.f('ix_performers_dancer_id'), table_name='performers')
    op.drop_index(op.f('ix_performers_category_id'), table_name='performers')
    op.drop_table('performers')
    op.drop_index(op.f('ix_categories_tournament_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_dancers_id'), table_name='dancers')
    op.drop_index(op.f('ix_dancers_email'), table_name='dancers')
    op.drop_index(op.f('ix_dancers_blaze'), table_name='dancers')
    op.drop_table('dancers')
    # ### end Alembic commands ###
