"""Add CANCELLED status to TournamentStatus enum

Revision ID: 8d4205ef8195
Revises: 2f62eedb0250
Create Date: 2025-12-03 14:28:16.562093

This migration adds the CANCELLED status to TournamentStatus enum for tournaments
that were active but stopped before completion (phases: PRESELECTION, POOLS, FINALS).

Status lifecycle after this change:
- CREATED → ACTIVE → COMPLETED (normal flow)
- ACTIVE → CANCELLED (admin intervention to stop in-progress tournament)

Note: SQLite doesn't support ALTER TYPE for enums, so the change is made at the
Python/SQLAlchemy model level only. The new 'cancelled' value will be accepted
by the database's TEXT column with CHECK constraint.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4205ef8195'
down_revision: Union[str, None] = '2f62eedb0250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite: No schema changes needed - enum values stored as TEXT
    # The new 'cancelled' value will be accepted by the status column
    # PostgreSQL users would need: ALTER TYPE tournamentstatus ADD VALUE 'cancelled';
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No rollback needed for SQLite (TEXT column)
    # PostgreSQL users: Cannot remove enum values, would need to recreate type
    pass
    # ### end Alembic commands ###
